### ISSUE TITLE
mismatched URIs in viewer grid for annotation-opened text resources

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#104]
When a text resource is added to the grid by clicking an annotation target, its URI as stored in the grids `containers` object sometimes differs from that stored in the dom data properties, causing an error when the document is made uneditable during close and failing to toggle editable off during drag, which in turn causes the text to disappear post-drag.

**Comment by SteveMarvin** [comment]
Another one I'm not sure how to test. I have not been able to get the text to disappear after a drag, but otherwise I'm not certain what to do here.

Rejected to flag for more testing details.

**Comment by SteveMarvin** [comment]
Andy and I spoke, and I think I understand this now, and it looks good from a testing perspective. I can't be sure what is happening under the hood (where things are stored, etc.).
