### ISSUE TITLE
"Loading" text on a moved frame

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#108]
When moving a text frame before it is fully loaded, if you move a text doc before it's loaded, the  "Loading . . ." alert text persists even after the text loads. See attached video for example.

https://cl.ly/3g401P1W2K0w

**Comment by SteveMarvin** [comment]
This seems to be fixed. I had to throttle the network down to almost nothing to get a text resource to take long enough to move a resource while it was loading. 👍
