### ISSUE TITLE
Missing image resource titles in rollover window

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#110]
When you hover over an annotation to display its rollover window, image resources should have both a thumbnail and title, but instead sometimes only show the thumbnail. 

I've been able to reproduce consistently by showing the rollover window for a resource in one project (image titles show up correctly), then switching projects and returning to the first project, then showing the rollover window again (no image titles displayed).

Possibly due to "ghost" rollover window elements that persist and misdirect jQuery selections after a project switch.

**Comment by SteveMarvin** [comment]
This is looking good. 👍
