### ISSUE TITLE
Resources' "What links here" Button Brings App to a Halt

### ISSUE THREAD

**Issue by gremid** [performant-software/DM#115]
Martin: 
> So I've been working a little more with the "corner icon" - the page icon in the top right corner on each DM document that serves as a target for links directly to the whole of the document - and my using it and linking to it appears to be causing some issues. [...], - once the weirdness hits like this, DM in generally seems to become pretty sluggish overall [...]

**Comment by gremid** [comment]
Appears to be a regression related to #55 and subsequent #89. 

By extending the graph traveral scope rooted in a resource, requesting subgraphs like 

http://dm.performantsoftware.com/store/projects/urn:uuid:6kgzvlttct53q9pyg29hjjcyhiefa1umdb2r/canvases/urn:uuid:5925b6e5-1e86-4e81-aec2-a524ef907258

pulls in to many data, slowing down the app.

**Comment by SteveMarvin** [comment]
I am not able to trigger any aberrant behavior with the corner icon.
