### ISSUE TITLE
Single User Mode

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#129]
We still need basic safeguards to ensure that two people cannot get on and edit the same project simultaneously - currently there is nothing in place to prevent that from happening, which, for obvious reasons, could lead to trouble.

**Comment by jamiefolsom** [comment]
@gremid's proposal: implement a REST endpoint to allow retrieval of logged on users and their open projects; make a dialog available to display those users/projects.

**Comment by gremid** [comment]
Implemented a REST endpoint `/store/projects/dashboard` (faa527a68c9454290fcc4ce389a219c159579fd5) which provides an overview of currently open projects. Each time a user switches to a project, the DM client posts to the same endpoint, registering the user's session with the current project.

@akstuhl: As discussed with Jamie yesterday, would you be so kind and implement a client-side feature that displays the dashboard to users so they are informed about potential conflicts when editing the same project concurrently. Thanks!
