### ISSUE TITLE
Window resizing label in popups scrolls with window

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/DM#131]
When a popup window is first drawn, the resizing pip in the lower right corner may be in the lower right, but if the user scrolls the window, the pip moves up with the scrolled window. This is peculiar, but not deadly. 

![screen shot 2017-06-20 at 4 13 44 pm](https://user-images.githubusercontent.com/18423533/27353912-d5ed6c68-55d3-11e7-89dc-b6bfdb5e7fd4.png)
![screen shot 2017-06-20 at 4 13 48 pm](https://user-images.githubusercontent.com/18423533/27353915-d8770e76-55d3-11e7-92f8-391703335d97.png)

**Comment by akstuhl** [comment]
Closed by #134
