### ISSUE TITLE
Reformatting text strips active state

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#133]
Reformatting text with highlights as bullet points strips out highlights' active state

* Make some text.

* Add active highlights with links

* Select this text and in the text editor, reformat it as a bullet or number list
![asdf](https://user-images.githubusercontent.com/882377/27448083-6a809c0a-5751-11e7-9f75-3c6a636c4d3c.png)

* Highlighted text will still display as yellow, but will no longer have any functionality

**Comment by akstuhl** [comment]
This is most likely a frontend-only issue caused by clashing HTML tags in the text resource. An interceding process like the one currently used to toggle highlight display could be appropriate here.
