### ISSUE TITLE
Content of text resource windows does not load

### ISSUE THREAD

**Issue by gremid** [performant-software/DM#14]
When opening a text resource, a new window is opened but the text's content is not loaded, leaving the window empty:

![image](https://cloud.githubusercontent.com/assets/695757/17433374/9b310e56-5b04-11e6-8904-36b57c235efe.png)

Trying to close such empty windows triggers an exception: 

```
Uncaught TypeError: Cannot read property 'uri' of null
    atb.viewer.ViewerGrid.removeViewerContainer @ all-js-code.js:767
    atb.viewer.ViewerContainer.close @ all-js-code.js:3210
    goog.events.fireListener @ all-js-code.js:445
    goog.events.handleBrowserEvent_ @ all-js-code.js:448
    (anonymous function) @ all-js-code.js:437
```

Empty windows also stay open when projects are switched.

**Comment by gremid** [comment]
Seems to be a duplicate of #10. I have not encountered this issue anymore.

**Comment by SteveMarvin** [comment]
I can no longer reproduce this. 👍
