### ISSUE TITLE
Project dropdown doesn't scroll

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#146]
Project dropdown doesn't scroll if there are more projects than can be displayed in the browser frame. In the image below - I can no longer get to the Virtual Mappa Project.

![image 1](https://user-images.githubusercontent.com/882377/29926098-6665cfe4-8e30-11e7-8148-3e295f74d3c5.png)

**Comment by akstuhl** [comment]
Duplicate of #149
