### ISSUE TITLE
If project menu is too long, all projects cannot be accessed

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#149]
If project menu is too long for a user, all projects cannot be accessed - no scrolling.

![image](https://user-images.githubusercontent.com/882377/30563866-3467b722-9c91-11e7-93d9-afc78ab74e12.png)

**Comment by akstuhl** [comment]
This requires a minor layout fix.

**Comment by jamiefolsom** [comment]
Closing as dupe of #146
