### ISSUE TITLE
As a user, I want to drag frames to different spots in the workspace

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#23]

**Comment by SteveMarvin** [comment]
Unless I am misunderstanding, this is not working for me. If I click on the title bar, it opens the title for renaming. If I click and drag, I highlight portions of the frame. If I change the Lock status, that still doesn't work. Am I misunderstanding what I am going for here?

**Comment by akstuhl** [comment]
@SteveMarvin just to confirm, this is on the staging server at http://67.207.158.85 right? It's possible you may need to shift+cmd+R to clear out cached JS files, but there could be something funkier going on

**Comment by akstuhl** [comment]
Here's a mid-drag action shot to illustrate what it should be doing (working for me on staging currently) 
<img width="1317" alt="dm-frames-screengrab" src="https://cloud.githubusercontent.com/assets/2431978/24774853/2810753c-1ae0-11e7-81d7-1a493caa1ee1.png">

**Comment by jamiefolsom** [comment]
Interesting. I thought maybe Andy and Gregor's deployments had overlapped.
Maybe as you say it's a caching issue. Command-Shift-N in Chrome creates an
incognito window which should prevent caching too.

**Comment by SteveMarvin** [comment]
Now working, looks like cache, as you said. Also works in Safari and Firefox.  ;-) 👍
