### ISSUE TITLE
As a user, I want to resize the rollover window

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#24]
- User preference.
- Editors should be able to set rollover window size to a per-project default.

**Comment by SteveMarvin** [comment]
Cannot resize rollover window, sorry.

**Comment by SteveMarvin** [comment]
Perfect! 👍  In Chrome and Safari. Clearing my cache did the trick. 

Firefox is having some issues with text windows loading, and so I can only get the rollover that pops up when I hover the page icon (annotation listing) in the upper right, and it is wonky. Don't think we're supporting FF at this time, so not going to reject this on that basis. ;-)

BTW, accidentally added a label, now removed.

**Comment by SteveMarvin** [comment]
Argh...OK, I didn't accidentally add a label, as I thought, so I unnecessarily deleted the right one. Instead I moved the issue to the wrong pipeline. Label put back, pipeline corrected. Issue accepted. Sorry for the juggling act.
