### ISSUE TITLE
As an editor, I want to files to open for editing to where I was while reading

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#32]
Related to #31 : When editing, if you are in edit mode in a doc and you open a link to another file from it, could it open in edit mode as well? Reason: often when working on something, you follow a link to edit it, it’s in a long text file, opens up to the exact spot, and then you have to enable editing, and it resets the text display to the top of the file.  Ideally, when you turn on editing for a file, it would open to the same place as you were in in the read only mode, and not reset to the top, but I’ve been told before that was not an option.

**Comment by SteveMarvin** [comment]
Heh, now that's a title!

**Comment by jamiefolsom** [comment]
Importing a buncha issues from an email -- quicker to dump whole description in the title, then edit down...

**Comment by SteveMarvin** [comment]
Hey, I'm not judging! Grandiloquence is a dying art...

**Comment by jamiefolsom** [comment]
@akstuhl is this one of the issues you fixed?

**Comment by jamiefolsom** [comment]
@akstuhl can you confirm whether this one is completed? Thanks!

**Comment by akstuhl** [comment]
@jamiefolsom not exactly as described here, but I believe the problem has been resolved. When you toggle editing on or off for a text resource, it no longer resets the scroll position to the top of the text frame.

**Comment by jamiefolsom** [comment]
@akstuhl is this delivered, and testable on staging? If so, would you move to delivered? Thanks!

**Comment by jamiefolsom** [comment]
(...and assign to @SteveMarvin)

**Comment by jamiefolsom** [comment]
@akstuhl ok for me to close this?
