### ISSUE TITLE
As an editor, I want to order the table of contents manually

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#33]
Have table of contents be ordered by an editor as opposed to being loaded alphabetically -  click and drag structure?

**Comment by jamiefolsom** [comment]
Front end is mostly complete, just need to wrap up storage of sequence of TOC items.

**Comment by jamiefolsom** [comment]
@gremid and @akstuhl need to coordinate on this one -- as I recall, ordered lists don't exist on the server side yet. Feel free to add any color commentary here about that effort. Thanks!

**Comment by gremid** [comment]
The server side code has been added and the feature is ready for testing:

1. Create a new project or open an existing one.
1. In the project viewer/ table of contents, drag text/image resources around, thereby changing their order.
1. Reload the browser or switch back and forth between projects.
1. The defined order should persist between reloads/project switches.

**Comment by SteveMarvin** [comment]
Success! 👍
