### ISSUE TITLE
Can't rename images

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#45]
We've encountered an issue trying to rename an uploaded image file within DM:

In Virtual Mappa, there is a new map (recently uploaded) named "PsalterListMapReallyBig" - this is the name it had when it was uploaded.

We have several times tried to rename it "Psalter List Map (BL Additional MS 28681, f. 9v)" by editing the title bar above the image display. 

When you edit it, the change appears to stick (and shows up changed in the Table of Contents as well) for the duration of the user being logged in, even if you change projects and then go back to Virtual Mappa. 

But if you log out and log back in again, the title reverts back to its former, original state.

**Comment by SteveMarvin** [comment]
Sorry, this is still happening. Text name changes are retained, but image renames are not after relog.

**Comment by SteveMarvin** [comment]
Nailed it! Images now retain changes to title and are there on relog.
