### ISSUE TITLE
Cannot delete project

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/DM#5]
Attempting to delete a project results in the following dialog:

![screen shot 2016-08-02 at 2 52 09 pm](https://cloud.githubusercontent.com/assets/18423533/17341042/c449558c-58c0-11e6-923c-3fe929a56296.png)

**Comment by gremid** [comment]
Fixed in 75aac39002a.

**Comment by SteveMarvin** [comment]
This is working across all latest supported browsers. 👍
