### ISSUE TITLE
Can add blank user

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/DM#6]
The add user function allows one to add a blank user just by hitting the "+" button when there is no text in the "Add a user" field.

**Comment by SteveMarvin** [comment]
Not quite. I can now only add one blank user, and by changing permissions in the adding row, I can modify that blank user, but only that one. What's more, that blank user is gone on relog. I doubt this is going to be a major problem. I'm rejecting it for now, but it is so minor we could probably live with it.

**Comment by gremid** [comment]
As the project sharing dialog has been redesigned and the problematic control been removed, this issue should be invalid now.

**Comment by SteveMarvin** [comment]
Issue obsolete, CLOSED
