### ISSUE TITLE
Text links from one document to another point to the top of the referent document

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#63]
In editing mode, clicking on a text link that points to a location later in another text document does not open the text doc to that location, but instead to the top of the document.   

The proper location briefly appears when the doc first loads, but then resets back to the top.

Note: opening a second, read only version of the same doc through the same link *does* open the new doc to the proper location. Also, it appears that in the public, read only mode, that this bug does not appear, and that links to text documents open to proper location.

**Comment by akstuhl** [comment]
This may be a separate issue, but I noted in meeting with Martin that I hadn't been able to reproduce this bug per my understanding of the description, and he clarified that there's a problem where edit-enabling (formerly "locking") a text resource resets its scroll position to the top.
