### ISSUE TITLE
Cannot close an image opened from a rollover link

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#64]
When you open an image in read/write mode for the first time from any annotated link, it shows the "x" box, which is disabled, and it cannot be closed. When you open it a second time (after closing the project, which the only way to close it).

EDIT (Martin, on 3/29): thought this issue was no longer be manifesting, but it appears to be back.

**Comment by SteveMarvin** [comment]
This appears to be behaving properly. I never saw the original behavior. I'm having no issues with rollover popups closing, or with windows closing under any circumstances. 

👍
