### ISSUE TITLE
Annotation titles inconsistently save

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#65]
- In the Old English Bell-tokens v.2 project
- I noticed that there was a typo in one of the image titles (1c. Old English: manuscript M.2r (CCCC 44, f. 2r [p.1]) - if it matters). 
- I opened it up, and clicked on the title to fix it. 
- I may have closed it before clicking outside the the title bar or something, because the change to the text didn't stick - it remained uncorrected in the Table of Contents list, so 
- I opened it again and made the change a second time to the image title. 
- This time it stuck, but then I noticed that all the text docs I already had open got stuck and do not seem to be saving:

![image](https://cloud.githubusercontent.com/assets/882377/25666753/68cb4fba-2fef-11e7-9305-d414802dc686.png)

This is the second time recently that I changed an existing title of a document in the title bar, and then I noticed save errors resulting. I figure you are still working on this, but I thought I should note it as something that is relatively persistent. 

[Update]: If you need a timestamp for it - it was May 3, 9:38AM (CST)

[Update 2]: The stuck  "saving . . ." display issue is not local, and does not appear to be prevent text from saving. 

Additional text docs opened within the project where the issue was generated  display the same stuck state. Further, opening a *different* project (in this case, Virtual Mappa, at May 3, 10:24AM (CST) shows the same stuck state - so what ever state error has occurred in  
the previous project displays across projects (see image). 

Happily, editorial changes to text docs stuck in (saving . . .) state seem to be actually being saved (at least in the subsequent Virtual Mappa example - I didn't test the stuck texts from the original problem in OE Belltokens v.2), and logging out and back in returns everything to normal. 

![image](https://cloud.githubusercontent.com/assets/882377/25668642/43666eac-2ff5-11e7-8714-15c2cd8f5aad.png)

**Comment by gremid** [comment]
67d6b0b08b10072052b637cac8409d19a45b95ac seems to be at fault.

**Comment by gremid** [comment]
The relevant code path has been aligned with text title changes.

**How to test**

Follow the scenario outlined in the issue's first comment.

**Comment by SteveMarvin** [comment]
I can not reproduce the bug after fix. ACCEPTED.
