### ISSUE TITLE
url for public link does not match the actual url generated by project

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#66]
url for public link for a project displayed in admin section does not match the actual url generated by project (note: this may be a vestige of older public project data- but it seems to be the case for public versions of both Virtual Mappa and Bell-Tokens v.2)

**Comment by SteveMarvin** [comment]
Not sure I can test this...does this staging server generate public URLs? Because at present all of them use the same one:

![screen shot 2017-04-11 at 11 31 16 am](https://cloud.githubusercontent.com/assets/18423533/24917224/7d61be06-1eaa-11e7-9946-a4213d9fe344.png)

**Comment by jamiefolsom** [comment]
Closing as solved. Note, per @SteveMarvin, that existing public URLs have to be removed and re-added to get the new, correct URLs. See: #90, TBD if we'll address that before releasing 1.0.
