### ISSUE TITLE
New users created from project page

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/DM#7]
New users can be created simply by adding them to the "Shared" list on the Project Info and Sharing page. They can even be admins from this page. However, they will then have passwords the same as their username, and cannot ever change that or add an email. If it is desired that this be a place where users can be created, this function should call the Create user function if the name doesn't exist already.

**Comment by gremid** [comment]
Users are not created within DM anymore but are taken over from an OAuth provider. In the sharing dialog, only users that have been authenticated before are present in the dropdown for assignment of project access rights.

The issue should be invalid/ solved now.

**Comment by SteveMarvin** [comment]
No longer valid
