### ISSUE TITLE
Set up an OAuth provider

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#72]
I will handle this one.

Probably using:
- Rails
- Devise
- Doorkeeper

@gremid and @akstuhl: make sense to you?

**Comment by gremid** [comment]
@akstuhl Done, right?

**Comment by akstuhl** [comment]
Just made one last tweak to the Performant-hosted to provider to auto-authorize when the request comes from DM (since DM is a trusted application and we don't need to confuse users with an additional dialog). So barring any other changes needed, this is done.
