### ISSUE TITLE
Create front end views for registration and login via OAuth provider(s)

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#74]
Redirects to OAuth provider (either ours or a public one)
- Register
- Login

**Comment by gremid** [comment]
In DM, except for the login dropdown menu, there are no UI-related changes. Google and GitHub provide their own registration/login functionality, Performant's provider has a those in place as well? @akstuhl Close?

**Comment by akstuhl** [comment]
Yep! Thanks @gremid.
