### ISSUE TITLE
Implement session storage on DM server to store the OAuth token

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#75]
The OAuth provider solution I am looking at for this is a gem for rails applications called Doorkeeper, which can issues its own 128 bit token, or can issue a JWT. Let me know if one is preferable to the other. Thanks!

**Comment by gremid** [comment]
Once authenticated against an external provider like Google or Performant, DM keeps track of the authorization token in its server-side session store. Entries there are referenced via identifiers stored in client-side cookies and are valid for up to 1 day by default.

**How to test**

1. Log into DM via any of the authentication providers.
1. Close browser tab/window or change to some other site.
1. Return to DM within a day: You should still be logged in and able to continue working.

**Comment by SteveMarvin** [comment]
Will have to test this over the weekend from home, not enough time left today.

**Comment by SteveMarvin** [comment]
If I shut Chrome down completely, I have to log back in when I bring it back up, and my workspace is empty. Assuming that is as desired, this appears to be working just fine.
