### ISSUE TITLE
Cannot edit existing users

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/DM#8]
Existing users cannot edit themselves, either their password or their email address. This is especially bad if their account was created using the Project Info and Sharing dialog (#7), so that now they can never edit their password or have an email address, and the username is forever taken.

**Comment by gremid** [comment]
@SteveMarvin We agreed with the customer to configure users via a CSV file passed on the command line, so I am removing the capability to edit users from the UI. (Will deal with #7 too)

**Comment by SteveMarvin** [comment]
Issue is now N/A. 👍
