### ISSUE TITLE
Re-enable title editing by clicking frame title when logged in

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#84]
Inadvertently disabled by #62. Title text click should reject drag event and toggle editing as before, while title-bar should accept drag event.

**Comment by SteveMarvin** [comment]
This does not work UNLESS the key icon ("click to lock resource for edit") is toggled, then one can both move the frame and edit the title. If the key is not depressed, one CANNOT click within the title to edit it, but one can move it. I see this as acceptable. 👍  Works A/S/F
