### ISSUE TITLE
Vertical layering bug in rollover window

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#87]
from Martin: "There's a weird glitch in the rollover display, where a rectangle of the underlayer of text shows through the rollover frame, along the top, right under the grey menu bar. See this image:"
![image](https://cloud.githubusercontent.com/assets/2431978/24886168/53839790-1e18-11e7-88c8-733f52d5cefd.png)

**Comment by SteveMarvin** [comment]
This appears to be fixed. 👍
