### ISSUE TITLE
Inconsistent text annotation target highlighting

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#97]
From Martin: "This one's more involved: the new visible/invisible highlights in text feature doesn't work correctly for a doc that's in an editable mode. In the Production version, everything you open opens to a default mode of editable, and I wonder if this was missed because on Staging docs were still opening in a default mode of locked/uneditable. 

What happens is: if you open a text file from a rollover link it doesn't open displaying *only* the linked to highlight, but still displays *all* the highlights (so, like it did before, and not parallel in function to how links work for displaying targets on images). 

Secondly, on a text document that is in editable mode, the "eye" icon doesn't work - toggling it doesn't toggle the visibility of the highlights as it should. (Note: it *does* work as it should in a Read Only mode of a doc)"

(See Martin's video - will send to @SteveMarvin over chat)

**Comment by SteveMarvin** [comment]
This appears to be working correctly now. 👍
