### ISSUE TITLE
Text no-highlight and selected classes persist in resource if window closed

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#99]
These classes should be removed upon loading any text resource so that highlights are not erroneously hidden or marked as selected

From Andy: if you open a text resource, set it to editable, toggle highlights to be hidden, and then make some change to the text (causing it to save), then reload the browser window and open that document again, it will incorrectly hide all the highlights

**Comment by SteveMarvin** [comment]
This no longer happens. One can no longer get the reloaded resource to hide highlights improperly. 👍
